apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeyedu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: honeyedu
  template:
    metadata:
      labels:
        app: honeyedu
    spec:
      imagePullSecrets:
       - name: my-registry-secret  # Add this line
      containers:
      - name: honeyedu
        image: saritha752/honeyedu:latest
        ports:
        - containerPort: 80